### PR TITLE
Github plugin

### PR DESCRIPTION
**Pull request by S0lll0s**
PR for #72, still WIP

### CODE REVIEW

**Comment by S0lll0s** [comment]
Except for commit/issue/etc notifications everything is working.

@JohnMaguire should `.issue web UI` only show one? currently I made it show at most 5 and tell the number of remaining ones.

**Comment by JohnMaguire** [comment]
@S0lll0s I did not notice the notifications for this pull request! Thank you again. Let me try this out when I get home. The only thing I will say is I'd like to avoid channel spam by default with Cardinal -- perhaps we could make it a config option, how many to show by default?

**Comment by S0lll0s** [comment]
That should be easy to do, should `null` mean *show all* or *use default settings*? You could also use a string ("all") to denote that setting.

**Comment by JohnMaguire** [comment]
I say `-1` for "show all", `null` for default, any other integer for a limit. :) Does that sound reasonable?

**Comment by S0lll0s** [comment]
Sounds good, done :P

**Comment by JohnMaguire** [comment]
Awesome, sorry I haven't gotten back to you on this yet! I'll try to take a look at this after work today. :) :+1:

**Pull request merged**
