### PR TITLE
Vagrant support

### PR DESCRIPTION
**Pull request by nullzion**
Support for Vagrant virtual machine. This should simplify development on various machines. Optionally there should be entry in Contributing section with info how to get Cardinal up and running with Vagrant.

### CODE REVIEW

**Comment by JohnMaguire** [comment]
Thanks for the PR! I've considered adding Vagrant or Docker support to Cardinal in the past, but can't think of a very good reason to.

The features Docker can provide are pretty much covered by `virtualenv`, and Vagrant feels like a pretty heavy dev dependency for something this lightweight to me.

The main thing I see this as being useful for is providing OpenSSL support without having to install it on the host machine -- but I'm not sure this is really a concern. I doubt most people really care if their IRC bot connects over SSL or not, and if they do, they likely already have OpenSSL installed on their system.

Is there any reason you'd prefer to use a Vagrant machine for Cardinal development? I really am open to the idea, I'm just not sure it's really worth the extra effort.

**Comment by nullzion** [comment]
Honestly, my main reason for adding Vagrant support was that I'm stuck on fresh installation of Windows and it seemed like huge hassle to get everything working properly. Vagrant was really simple alternative to have everything running contained with easy package manager.

I wouldn't refer to Vagrant as dependency, more like optional way to run or develop Cardinal on.

**Comment by JohnMaguire** [comment]
Hmm, I can see how it would be useful to make supporting Windows easier -- I believe the code should run under Windows but I haven't tested it in a very long time. And I am very familiar with how painful setting up a Python environment on Windows can be.

However, it does require that you setup a Vagrant environment instead. Is this process drastically easier on Windows? I'm also concerned about having to maintain the dependencies, and updating the Vagrant base image.

Docker seems a little more lightweight and maybe like a better fit for Cardinal -- have you used it on Windows? I'm wondering how much more difficult it is to configure than Vagrant. If the difference is marginal, I might get around to adding a Dockerfile soon.

**Comment by JohnMaguire** [comment]
Closing this for now. Thanks for submitting it though!

Docker might actually be kinda neat (would make the install process for people who don't care about writing plugins possibly super-duper easy.) It'd especially be cool if we could come up with a way to make a Dockerfile others can use as a base to include their own plugins in. Then you can have different "flavors" of Cardinal pretty easily.

**Pull request closed without merging**
