### PR TITLE
Feature/movie

### PR DESCRIPTION
**Pull request by target111**
Implement movie plugin. The plugin returns information about a movie using the omdb api.

### CODE REVIEW

**Comment by JohnMaguire** [comment]
Finally getting around to reviewing this... I squashed your commits, and fixed some lint errors on this branch: https://github.com/JohnMaguire/Cardinal/tree/feature/movie-plugin

Just applied for an OMDb API key but it's taking a while to receive, so it'll have to wait for now.

**Comment by target111** [comment]
I can send you my api key if you still haven't got yours. Also if you're interested you can join us over at irc.anonops.com:6697 #cardinal to test some of the other plugins from my pull requests. (if you join and I'm not online know that the bot responds to '=' )

**Comment by JohnMaguire** [comment]
Again, sorry for letting this languish for 2 years! I'm not sure I want to run with OMDb. I may investigate something with Rotten Tomatoes or similar. Thank you so much for this contribution though!

**Comment by JohnMaguire** [comment]
Hey, I did end up merging this actually in 021d447851e0c7ecf0ab2326fb83e8812bb0a6aa. Thanks a bunch for the PR!

**Pull request closed without merging**
